image: openjdk:13-alpine

before_script:
  - apk add --no-cache make git
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - compile
  - unit test
  - package
  - quality
  - publish

#compile:
#  stage: compile
#  only:
#    - master
#    - develop
#  script:
#    - make core-compile
#  artifacts:
#    paths:
#      - build/
#      - application/build/
#      - application/authentication-keycloak/build/
#  allow_failure: false

unit-test:
  stage: unit test
  only:
    - master
    - develop
#  dependencies:
#    - compile
  script:
    - make core-test
  artifacts:
    paths:
      - build/
      - application/build/
      - application/authentication-keycloak/build/
  allow_failure: false

#code-analysis:
#  stage: quality
#  only:
#    - master
#    - develop
#  script:
#    - make core-code-analysis
#  dependencies:
#    - unit-test
#  when: on_success

after_script:
  - echo "End CI"