image: gradle:6.7-jdk11

before_script:
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - compile
  - unit test
  - package
  - quality
  - publish

compile:
  stage: compile
  only:
    - master
    - develop
  script:
    - gradle -g .gradle/caches clean assemble
  artifacts:
    paths:
      - build/
      - application/build/
      - application/authentication-keycloak/build/
  allow_failure: false

unit-test:
  stage: unit test
  only:
    - master
    - develop
  dependencies:
    - compile
  script:
    - gradle -g .gradle/caches check
  artifacts:
    paths:
      - build/
      - application/build/
      - application/authentication-keycloak/build/
  allow_failure: false

sonarqube:
  stage: quality
  only:
    - master
    - develop
  script:
    - gradle sonarqube
  dependencies:
    - unit-test
  when: on_success

after_script:
  - echo "End CI"