image: openjdk:13-slim

before_script:
#  - apk add --no-cache make git
  - apt-get update && apt-get install -y make curl git jq
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - compile
  - unit test
  - package
  - quality
  - publish
  - trigger_deploy_ci
#  - trigger_deploy

#compile:
#  stage: compile
#  only:
#    - master
#    - develop
#  script:
#    - make core-compile
#  artifacts:
#    paths:
#      - build/
#      - application/build/
#      - application/authentication-keycloak/build/
#  allow_failure: false
#  tags:
#    - java

unit-test:
  stage: unit test
  only:
    - master
    - develop
#  dependencies:
#    - compile
  script:
    - make core-test
  artifacts:
    paths:
      - build/
      - application/build/
      - application/authentication-keycloak/build/
  allow_failure: false
  tags:
    - java

code-analysis:
  stage: quality
  #image: sonarsource/sonar-scanner-cli
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: https://ci.tricefal.io/sonar
    SONAR_ANALYSIS_MODE: publish
  only:
    - master
    - develop
  script:
    - gitlab-sonar-scanner
  dependencies:
    - unit-test
  when: on_success

#code-analysis:
#  stage: quality
#  image: sonarsource/sonar-scanner-cli
#  only:
#    - master
#    - develop
#  script:
#    - docker run -e SONAR_HOST_URL=http://ci.tricefal.io/sonar -v .:/usr/src sonarsource/sonar-scanner-cli
#  dependencies:
#    - unit-test
#  when: on_success

trigger_deploy_ci:
  stage: trigger_deploy_ci
  variables:
    CICD_PROJECT_ID: 18283923
  script:
    - curl -s -X POST -F token=$CI_JOB_TOKEN -F ref=develop -F "variables[TRIGGERER_PIPELINE_ID]=${CI_PIPELINE_ID}" https://gitlab.com/api/v4/projects/${INFRA_PROJECT_ID}/trigger/pipeline | tee res.json
    - cat res.json
  artifacts:
    paths:
      - res.json

after_script:
  - echo "End CI"