version: "3.6"

services:

  dbsignup:
    image: postgres:13.1
    container_name: dbsignup
    hostname: dbsignup
    networks:
      - internal-subnet
    env_file:
      - ./config/dbsignup.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbsignup_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: registry.gitlab.com/tricefal/docker-keycloak:${VERSION}
    container_name: keycloak
    hostname: keycloak
    networks:
      - internal-subnet
    ports:
      - "1080:8080"
      - "1443:8443"
    depends_on:
      - dbkeycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbkeycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Pa55w0rd
      - PROXY_ADDRESS_FORWARDING=true
    restart: unless-stopped

  dbkeycloak:
    image: postgres:13.1
    container_name: dbkeycloak
    hostname: dbkeycloak
    networks:
      - internal-subnet
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - dbkeycloak_data:/var/lib/postgresql/data
    restart: always

networks:
  internal-subnet:
    name: internal_subnet

volumes:  
  signup_files:
  signup_logs:
  dbsignup_data:
  dbkeycloak_data:
