# ENV=dev
# ENABLE_BUILD=false
# VERSION=latest
# We will built custom images for :
# - core
# - proxy

version: "3.6"

services:
  core:
    image: registry.gitlab.com/tricefal/tricefal/core:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        ENABLE_BUILD: ${ENABLE_BUILD}
    container_name: core
    hostname: docker_core
    networks:
      - internal-subnet
    env_file:
      - ./config/core.docker.env
    volumes:
      - ./config/core.docker.env:/app/config/app.env:ro
      - core_files:/data/files:rw
      - core_logs:/data/logs:rw
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - dbcore
    restart: unless-stopped

  dbcore:
    image: postgres:13.1
    container_name: dbcore
    hostname: docker_dbcore
    networks:
      - internal-subnet
    env_file:
      - ./config/dbcore.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbcore_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    restart: unless-stopped

  dbkeycloak:
    image: postgres:13.1
    container_name: dbkeycloak
    hostname: docker_dbkeycloak
    networks:
      - internal-subnet
    restart: always
    env_file:
      - ./config/dbkeycloak.env
    volumes:
      - dbkeycloak_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    hostname: docker_keycloak
    networks:
      - internal-subnet
    # ports:
    #   - "1080:8080"
    #   - "1443:8443"
    depends_on:
      - dbkeycloak
    env_file:
      - ./config/keycloak.env
    volumes:
      - ./config/keycloak/${ENV}/:/opt/jboss/keycloak/imports/:rw
      - ./config/certs/${ENV}/${ENV}.tricefal.io.fullchain.pem:/etc/x509/https/tls.crt:ro
      - ./config/certs/${ENV}/${ENV}.tricefal.io.key:/etc/x509/https/tls.key:ro
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.profile.feature.docker=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    restart: unless-stopped

networks:
  internal-subnet:
    name: internal_subnet

volumes:  
  core_files:
  core_logs:
  dbcore_data:
  dbkeycloak_data:
