# VERSION=latest
# ENV=dev
# ENABLE_BUILD=false

version: "3.6"

services:
  core-app-signup:
    image: registry.gitlab.com/tricefal/tricefal-core/core-app-signup:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        ENABLE_BUILD: ${ENABLE_BUILD}
    container_name: core
    hostname: docker_core
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.21
    extra_hosts:
      - "docker_keycloak_1:172.28.5.11"
      - "docker_dbcore:172.28.5.20"
    env_file:
      - ./config/core-app.${ENV}.env
    volumes:
      - ./.run:/app/.run
      - ./config/core-app.${ENV}.env:/app/config/core-app.env:ro
      - core_files:/data/files:rw
      - core_logs:/data/logs:rw
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - dbcore
    restart: unless-stopped

  dbcore:
    image: postgres:13.1
    container_name: dbcore
    hostname: docker_dbcore
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.20
    env_file:
      - ./config/dbcore.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbcore_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: registry.gitlab.com/tricefal/tricefal-keycloak/keycloak:${VERSION}
    container_name: keycloak
    hostname: docker_keycloak_1
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.11
    extra_hosts:
      - "docker_dbkeycloak:172.28.5.10"
    ports:
      - "1080:8080"
      - "1443:8443"
    depends_on:
      - dbkeycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=docker_dbkeycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Pa55w0rd
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./config/${ENV}/:/opt/jboss/keycloak/imports/:rw
    restart: unless-stopped

  dbkeycloak:
    image: postgres:13.1
    container_name: dbkeycloak
    hostname: docker_dbkeycloak
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.10
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - dbkeycloak_data:/var/lib/postgresql/data
    restart: always

networks:
  internal-subnet:
    name: internal_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24

volumes:  
  core_files:
  core_logs:
  dbcore_data:
  dbkeycloak_data:
