# VERSION=latest
# ENV=dev
# ENABLE_BUILD=false

version: "3.6"

services:
  app-signup-backend:
    image: registry.gitlab.com/oneprofile/app-signup-backend:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        ENABLE_BUILD: ${ENABLE_BUILD}
    container_name: signup
    hostname: signup
    networks:
      - internal-subnet
    extra_hosts:
      - "dbsignup:172.28.5.20"
    env_file:
      # using keycloak on DEV
      - ./config/app.dev.env
    volumes:
      - ./.run:/app/.run
      - ./config/app.dev.env:/app/config/app.env:ro
      - signup_files:/data/files:rw
      - signup_logs:/data/logs:rw
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - dbsignup
    restart: unless-stopped

  dbsignup:
    image: postgres:13.1
    container_name: dbsignup
    hostname: dbsignup
    networks:
      - internal-subnet
    env_file:
      - ./config/dbsignup.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbsignup_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  internal-subnet:
    name: internal_subnet
volumes:  
  signup_files:
  signup_logs:
  dbsignup_data:
  dbkeycloak_data:
