version: "3.6"
networks:
  internal-subnet:
    name: internal_subnet
services:
  core:
    image: openjdk:12-alpine
    container_name: core
    hostname: core
    networks:
      - internal-subnet
    volumes:
      - ./application/authentication-keycloak/build/libs:/app/
      - data/files:/data/files:rw
      - data/logs:/data/logs:rw
    env_file:
      - ../../config/core.env
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - postgres-core
    command: java ${DEBUG_ARG} -jar /app/auth-keycloak-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=localhost

  postgres-core:
    image: postgres:10.5
    container_name: postgres-core
    hostname: docker_postgres-core
    volumes:
      - ./application/authentication-keycloak/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/authentication-keycloak/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - data/postgres-core:/var/lib/postgresql/data:rw
    env_file:
      - config/postgres-core.env
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    networks:
      - internal-subnet