# VERSION=latest
# ENV=dev
# ENABLE_BUILD=false

version: "3.6"

services:
  app-signup-backend:
    image: registry.gitlab.com/oneprofile/app-signup-backend:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        #ENV: ${ENV}
        ENABLE_BUILD: ${ENABLE_BUILD}
    container_name: app-signup-backend
    hostname: app-signup-backend
    networks:
      - internal-subnet
    env_file:
      - ./config/app.local.env
    volumes:
      - ./.run:/app/.run
      - ./config/app.local.env:/app/config/app.env:ro
      - signup_files:/data/files:rw
      - signup_logs:/data/logs:rw
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - dbsignup
    restart: unless-stopped

  dbsignup:
    image: postgres:13.1
    container_name: dbsignup
    hostname: dbsignup
    networks:
      - internal-subnet
    env_file:
      - ./config/dbsignup.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbsignup_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:12.0.3
    container_name: keycloak
    hostname: keycloak
    networks:
      - internal-subnet
    ports:
      - "1080:8080"
      - "1443:8443"
    depends_on:
      - dbkeycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbkeycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Pa55w0rd
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./config/keycloak/:/opt/jboss/keycloak/imports/:rw
      - ./certs/local/local.cert.fullchain.pem:/etc/x509/https/tls.crt:ro
      - ./certs/local/local.cert.key:/etc/x509/https/tls.key:ro
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.profile.feature.docker=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    restart: unless-stopped

  dbkeycloak:
    image: postgres:13.1
    container_name: dbkeycloak
    hostname: dbkeycloak
    networks:
      - internal-subnet
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - dbkeycloak_data:/var/lib/postgresql/data
    restart: always

networks:
  internal-subnet:
    name: internal_subnet

volumes:  
  signup_files:
  signup_logs:
  dbsignup_data:
  dbkeycloak_data:
