# VERSION=latest
# ENV=dev
# ENABLE_BUILD=false

version: "3.6"

services:
  core-app-signup:
    image: registry.gitlab.com/tricefal/tricefal-core/core-app-signup:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        ENABLE_BUILD: ${ENABLE_BUILD}
    container_name: core
    hostname: docker_core
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.21
    extra_hosts:
      - "docker_keycloak_1:172.28.5.11"
    env_file:
      # using keycloak on CI
      - ./config/core-app.ci.env
    volumes:
      - ./.run:/app/.run
      - ./config/core-app.ci.env:/app/config/core-app.env:ro
      - core_files:/data/files:rw
      - core_logs:/data/logs:rw
    ports:
      - "8080:8080"
      - "5080:5080"
    depends_on:
      - dbcore
    restart: unless-stopped

  dbcore:
    image: postgres:13.1
    container_name: dbcore
    hostname: docker_dbcore
    networks:
      - internal-subnet
    env_file:
      - ./config/dbcore.env
    volumes:
      - ./application/signup/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./application/signup/src/main/resources/ref-data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/pricer-schema.sql:ro
      - ./infrastructure/pricer-reference/src/main/resources/data.sql:/docker-entrypoint-initdb.d/pricer-data.sql:ro
      - dbcore_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  internal-subnet:
    name: internal_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24

volumes:  
  core_files:
  core_logs:
  dbcore_data:
  dbkeycloak_data: