rootProject.name = "tricefal-core"

include(":application")
include(":application:signup")

include(":domain")
include(":domain:company")
include(":domain:freelance")
include(":domain:metafile")
include(":domain:mission")
include(":domain:notification")
include(":domain:pricer")
include(":domain:signup")

include(":infrastructure")
include(":infrastructure:company")
include(":infrastructure:cgu")
include(":infrastructure:freelance")
include(":infrastructure:encryption")
include(":infrastructure:ip-address")
include(":infrastructure:keycloak-client")
include(":infrastructure:login")
include(":infrastructure:mission")
include(":infrastructure:notification")
include(":infrastructure:pricer-reference")
include(":infrastructure:profile")
include(":infrastructure:signup")
include(":infrastructure:storage")
include(":infrastructure:user")

include(":shared")
include(":shared:util")
include(":shared:sso-keycloak-adapter")