server:
    servlet:
        context-path: /api

security:
    oauth:
        issuer: ${OKTA_OAUTH2_ISSUER}
        audience: ${OKTA_OAUTH2_AUDIENCE}
        client-id: ${OKTA_OAUTH2_CLIENT_ID}
        client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}

#    jwt:
#        key-store: classpath:keystore.jks
#        key-store-password: letmein
#        key-pair-alias: mytestkey
#        key-pair-password: changeme

spring:
    datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        platform: postgresql
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
#    liquibase:
#        change-log=classpath: db/changelog/db.changelog-master.xml

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB

#javax:
#    persistence:
#        schema-generation:
#            scripts:
#                create-target: schema.sql

logging:
#    config: classpath:logback-spring.xml
    file: core.log

data:
    files:
        path: /data/files/resumes