create table ref_pricer (
    id int8 generated by default as identity,
    last_date timestamp,
    nb_days_year int,
    comm_phase1 int,
    employer_charge int,
    insurance int,
    resto_daily int,
    resto_employer int,
    navigo_yr_fee int,
    navigo_yr_employer int,
    primary key (id)
);

insert into ref_pricer (1, NOW(), 217, 10, 45, 50, 10, 50, 827, 50)