create table ref_pricer (
    id int8 generated by default as identity,
    last_date timestamp,
    nb_days_year int,
    comm_phase1 int,
    employer_charge int,
    insurance int,
    resto_daily int,
    resto_employer int,
    navigo_yr_fee int,
    navigo_yr_employer int,
    payslip_mtly_fee int,
    primary key (id)
);
