create table meta_file (id int8 generated by default as identity, creation_date timestamp, filename varchar(50), type varchar(50), username varchar(50), primary key (id));
create table login (id int8 generated by default as identity, ip_address varchar(30), last_login timestamp, success boolean, username varchar(50), primary key (id));
create table signup (id int8 generated by default as identity, firstname varchar(50), lastname varchar(50), phone varchar(50), signup_date timestamp, status varchar(50), username varchar(50), primary key (id));
