
notification:
    mail:
        from: ${MAIL_FROM}
        admin: ${MAIL_ADMIN}

spring:
    mail:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT}
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
