rootProject.name = "app-signup-infrastructure"

include("cgu")
include("compnay")
include("encryption")
include("freelance")
include("ip-address")
include("login")
include("mission")
include("notification")
include("keycloak-client")
include("pricer-refernce")
include("profile")
include("signup")
include("storage")
include("user")
