rootProject.name = "tricefal-infrastructure"

include("cgu")
include("compnay")
include("encryption")
include("freelance")
include("ip-address")
include("login")
include("mission")
include("notification")
include("note")
include("keycloak-client")
include("pricer-refernce")
include("profile")
include("signup")
include("storage")
